DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd ; 
USE bd;

/* tabelas somente com primaras */
CREATE TABLE faculdade (
ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45) NOT NULL,

PRIMARY KEY(ID)
);
CREATE TABLE curso (
ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
NOMECURSO VARCHAR(30) NOT NULL UNIQUE,

PRIMARY KEY (ID)
);
CREATE TABLE vestibular 
(
  ID  SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL  ,
  DATAPROVA DATE NOT NULL ,
  PRIMARY KEY (ID)
);

 CREATE TABLE supervisor(
 CPF  VARCHAR(11) PRIMARY KEY NOT NULL , 
 NOME VARCHAR(30) NOT NULL
 
 );
   CREATE TABLE vestibulando 
 (
 EMAIL VARCHAR (45) NOT NULL UNIQUE ,
 CPF VARCHAR (11) NOT NULL UNIQUE,
 
 PRIMARY KEY (CPF)
 );

/*tabela intermediaria n:n */
CREATE TABLE oferece 
(
 IDCURSO SMALLINT UNSIGNED ,
 IDFACULDADE SMALLINT UNSIGNED,
 IDVESTIBULAR  SMALLINT UNSIGNED,
 VAGAS SMALLINT UNSIGNED NOT NULL,
 NOTACORTE DECIMAL(10,4),
 
 PRIMARY KEY (IDCURSO,IDFACULDADE,IDVESTIBULAR),
 FOREIGN KEY (IDCURSO) REFERENCES curso(ID),
 FOREIGN KEY (IDFACULDADE) REFERENCES faculdade(ID),
 FOREIGN KEY (IDVESTIBULAR) REFERENCES  vestibular(ID)
 );
 CREATE TABLE presta 
 (
 CPF  VARCHAR (11) ,
 IDVESTIBULAR SMALLINT UNSIGNED,
 
 PRIMARY KEY(CPF,IDVESTIBULAR) ,
 FOREIGN KEY ( CPF ) REFERENCES vestibulando (CPF),
 FOREIGN KEY ( IDVESTIBULAR ) REFERENCES vestibular ( ID)
 );
 
 /*tabela com fk*/

 CREATE TABLE unidade (
ID SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
RUA VARCHAR (30),
NUMERO SMALLINT UNSIGNED NOT NULL,
BAIRRO VARCHAR(30)
);

CREATE TABLE sala(
NUMERO SMALLINT UNSIGNED  NOT NULL , 
IDUNIDADE SMALLINT UNSIGNED NOT NULL,
QUANTIDADE_ALUNOS_SALA SMALLINT UNSIGNED NOT NULL ,
CPF_SUPERVISOR  VARCHAR(11) UNIQUE ,

PRIMARY KEY(NUMERO,IDUNIDADE),
FOREIGN KEY (IDUNIDADE) REFERENCES unidade (ID),
FOREIGN KEY(CPF_SUPERVISOR) REFERENCES supervisor (CPF)
);

/* novo */
CREATE TABLE alocacao (
CPF VARCHAR(11) NOT NULL,
IDVESTIBULAR SMALLINT UNSIGNED NOT NULL,
NUMERO SMALLINT UNSIGNED NOT NULL,
IDUNIDADE SMALLINT UNSIGNED NOT NULL,
PRESENCA BOOLEAN,

PRIMARY KEY (CPF, IDVESTIBULAR),

FOREIGN KEY (CPF, IDVESTIBULAR)
    REFERENCES presta(CPF, IDVESTIBULAR),

FOREIGN KEY (NUMERO, IDUNIDADE)
    REFERENCES sala(NUMERO, IDUNIDADE)
);
