DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd ; 
USE bd;

/* tabelas somente com primaras */
CREATE TABLE faculdade (
ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45) NOT NULL,

PRIMARY KEY(ID)
);
CREATE TABLE curso (
ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
NOMECURSO VARCHAR(30) NOT NULL UNIQUE,

PRIMARY KEY (ID)
);
CREATE TABLE vestibular 
(
  ID  TINYINT UNSIGNED AUTO_INCREMENT NOT NULL  ,
  DATAPROVA DATE NOT NULL ,
  PRIMARY KEY (ID)
);
 CREATE TABLE vestibulando 
 (
 EMAIL VARCHAR (45) NOT NULL ,
 CPF VARCHAR (11) NOT NULL UNIQUE,
 
 PRIMARY KEY (CPF)
 );
  

/*tabela intermediaria n:n */
CREATE TABLE oferece 
(
 IDCURSO SMALLINT UNSIGNED  ,
 IDFACULDADE SMALLINT UNSIGNED,
 IDVESTIBULAR  TINYINT UNSIGNED,
 VAGAS SMALLINT UNSIGNED NOT NULL,
 NOTACORTE DECIMAL(10,4),
 
 PRIMARY KEY (IDCURSO,IDFACULDADE,IDVESTIBULAR),
 FOREIGN KEY (IDCURSO) REFERENCES curso(ID),
 FOREIGN KEY (IDFACULDADE) REFERENCES faculdade(ID),
 FOREIGN KEY (IDVESTIBULAR) REFERENCES  vestibular(ID)
 );
 CREATE TABLE presta 
 (
 CPF  VARCHAR (11) ,
 IDVESTIBULAR TINYINT UNSIGNED,
 
 PRIMARY KEY(CPF,IDVESTIBULAR) ,
 FOREIGN KEY ( CPF ) REFERENCES vestibulando (CPF),
 FOREIGN KEY ( IDVESTIBULAR ) REFERENCES vestibular ( ID)
 );
