DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd ; 
USE bd;

/* tabelas somente com primaras */
CREATE TABLE curso (
ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
NOMECURSO VARCHAR(30) NOT NULL UNIQUE,

PRIMARY KEY (ID)
);

CREATE TABLE vestibular 
(
  ID  SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  DATAPROVA DATE NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE supervisor(
 CPF  VARCHAR(11) PRIMARY KEY NOT NULL, 
 NOME VARCHAR(30) NOT NULL
);

CREATE TABLE vestibulando 
(
 EMAIL VARCHAR (45) NOT NULL UNIQUE,
 CPF VARCHAR (11) NOT NULL UNIQUE,
 
 PRIMARY KEY (CPF)
);

/* tabela intermediaria n:n (agora binária) */
CREATE TABLE oferece 
(
 IDCURSO SMALLINT UNSIGNED,
 IDVESTIBULAR  SMALLINT UNSIGNED,
 VAGAS SMALLINT UNSIGNED NOT NULL,
 NOTACORTE DECIMAL(10,4),
 
 PRIMARY KEY (IDCURSO, IDVESTIBULAR),
 FOREIGN KEY (IDCURSO) REFERENCES curso(ID),
 FOREIGN KEY (IDVESTIBULAR) REFERENCES vestibular(ID)
);

CREATE TABLE presta 
(
 CPF  VARCHAR (11),
 IDVESTIBULAR SMALLINT UNSIGNED,
 
 PRIMARY KEY(CPF, IDVESTIBULAR),
 FOREIGN KEY (CPF) REFERENCES vestibulando (CPF),
 FOREIGN KEY (IDVESTIBULAR) REFERENCES vestibular (ID)
);

/* tabela com fk */
CREATE TABLE unidade (
ID SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
RUA VARCHAR (30),
NUMERO SMALLINT UNSIGNED NOT NULL,
BAIRRO VARCHAR(30)
);

CREATE TABLE sala(
NUMERO SMALLINT UNSIGNED NOT NULL, 
IDUNIDADE SMALLINT UNSIGNED NOT NULL,
QUANTIDADE_ALUNOS_SALA SMALLINT UNSIGNED NOT NULL,
CPF_SUPERVISOR VARCHAR(11) UNIQUE,

PRIMARY KEY(NUMERO, IDUNIDADE),
FOREIGN KEY (IDUNIDADE) REFERENCES unidade (ID),
FOREIGN KEY (CPF_SUPERVISOR) REFERENCES supervisor (CPF)
);

/* alocação */
CREATE TABLE alocacao (
CPF VARCHAR(11) NOT NULL,
IDVESTIBULAR SMALLINT UNSIGNED NOT NULL,
NUMERO SMALLINT UNSIGNED NOT NULL,
IDUNIDADE SMALLINT UNSIGNED NOT NULL,
PRESENCA BOOLEAN,

PRIMARY KEY (CPF, IDVESTIBULAR),

FOREIGN KEY (CPF) REFERENCES vestibulando(CPF),
FOREIGN KEY (IDVESTIBULAR) REFERENCES vestibular(ID),
FOREIGN KEY (NUMERO, IDUNIDADE) REFERENCES sala(NUMERO, IDUNIDADE)
);
 
 /* CURSOS */
INSERT INTO curso (NOMECURSO) VALUES
('Engenharia'),
('Medicina'),
('Direito'),
('Computacao'),
('Arquitetura');


/* VESTIBULARES */
INSERT INTO vestibular (DATAPROVA) VALUES
('2026-06-15'),
('2026-07-20'),
('2026-08-10');


/* SUPERVISORES */
INSERT INTO supervisor (CPF, NOME) VALUES
('11111111111', 'Carlos Silva'),
('22222222222', 'Ana Souza'),
('33333333333', 'Pedro Lima');


/* VESTIBULANDOS */
INSERT INTO vestibulando (EMAIL, CPF) VALUES
('joao@email.com', '44444444444'),
('maria@email.com', '55555555555'),
('ana@email.com', '66666666666'),
('paulo@email.com', '77777777777'),
('lucas@email.com', '88888888888');


/* OFERECE (curso + vestibular) */
INSERT INTO oferece (IDCURSO, IDVESTIBULAR, VAGAS, NOTACORTE) VALUES
(1,1, 50, 720.5000),
(2,1, 30, 800.0000),
(3,2, 40, 650.2500),
(4,2, 60, 600.0000),
(5,3, 25, 700.0000);


/* PRESTA (inscrições) */
INSERT INTO presta (CPF, IDVESTIBULAR) VALUES
('44444444444', 1),
('55555555555', 1),
('66666666666', 2),
('77777777777', 2),
('88888888888', 3);


/* UNIDADES */
INSERT INTO unidade (RUA, NUMERO, BAIRRO) VALUES
('Rua A', 100, 'Centro'),
('Rua B', 200, 'Jardim'),
('Rua C', 300, 'Industrial');


/* SALAS */
INSERT INTO sala (NUMERO, IDUNIDADE, QUANTIDADE_ALUNOS_SALA, CPF_SUPERVISOR) VALUES
(1,1, 30, '11111111111'),
(2,1, 25, '22222222222'),
(1,2, 40, '33333333333'),
(2,2, 35, NULL);


/* ALOCACAO */
INSERT INTO alocacao (CPF, IDVESTIBULAR, NUMERO, IDUNIDADE, PRESENCA) VALUES
('44444444444', 1, 1, 1, TRUE),
('55555555555', 1, 2, 1, FALSE),
('66666666666', 2, 1, 2, TRUE),
('77777777777', 2, 2, 2, NULL),
('88888888888', 3, 1, 1, TRUE);

-- alunos e suas salas
SELECT * FROM alocacao;

-- alunos por vestibular
SELECT * FROM presta WHERE IDVESTIBULAR = 1;

-- cursos disponíveis em cada vestibular
SELECT * FROM oferece;

-- join completo
SELECT v.CPF, a.IDVESTIBULAR, a.NUMERO, a.IDUNIDADE
FROM vestibulando v
JOIN alocacao a ON v.CPF = a.CPF;
 
